# https://github.com/benmosher/eslint-plugin-import/issues/2164
nodeLinker: node-modules

packageExtensions:
  "@putout/compare@8":
    peerDependencies:
      try-catch: "*"
  "@putout/engine-parser@4":
    peerDependencies:
      try-catch: "*"
  "@putout/engine-processor@>=3 <5":
    peerDependencies:
      "@babel/preset-env": "*"
  "@putout/operator-add-args@2":
    peerDependencies:
      try-catch: "*"
  "@putout/operator-declare@3":
    peerDependencies:
      try-catch: "*"
  "@putout/traverse@4":
    peerDependencies:
      try-catch: "*"
  "@shopify/eslint-plugin@42":
    peerDependencies:
      "@babel/core": "*"
      prettier: "*"
  eslint-config-hardcore@25:
    peerDependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
  eslint-plugin-styled-components-a11y@1:
    peerDependencies:
      eslint: "*"
      eslint-plugin-import: "*"
      eslint-plugin-react: "*"
  putout@24:
    peerDependencies:
      "@babel/preset-env": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
