packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2":
    peerDependencies:
      typescript: "*"
  "@putout/engine-loader@4.4.1":
    peerDependencies:
      "@babel/preset-env": "*"
  "@putout/engine-processor@>=3 <5":
    peerDependencies:
      "@babel/preset-env": "*"
  "@putout/compare@7":
    peerDependencies:
      try-catch: "*"
  "@putout/engine-parser@4":
    peerDependencies:
      try-catch: "*"
  "@putout/traverse@3":
    peerDependencies:
      try-catch: "*"
  "@shopify/eslint-plugin@40.4.0":
    peerDependencies:
      graphql: "*"
      prettier: "*"
      typescript: "*"
  eslint-config-hardcore@19.16.0:
    peerDependencies:
      "@babel/preset-env": "*"
      graphql: "*"
  eslint-plugin-graphql@4.0.0:
    peerDependencies:
      typescript: "*"
  graphql-config@3.3.0:
    peerDependencies:
      typescript: "*"
  "putout@>=16 <19":
    peerDependencies:
      "@babel/preset-env": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
