packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependencies:
      typescript: "*"
  "@putout/engine-loader@4.3.1":
    peerDependencies:
      "@babel/preset-env": "*"
  "@putout/engine-processor@3.2.0":
    peerDependencies:
      "@babel/preset-env": "*"
  "@shopify/eslint-plugin@*":
    peerDependencies:
      graphql: "*"
      prettier: "*"
      typescript: "*"
  eslint-config-hardcore@*:
    peerDependencies:
      "@babel/preset-env": "*"
      graphql: "*"
  eslint-plugin-graphql@*:
    peerDependencies:
      typescript: "*"
  graphql-config@*:
    peerDependencies:
      typescript: "*"
  putout@*:
    peerDependencies:
      "@babel/preset-env": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
