# https://github.com/benmosher/eslint-plugin-import/issues/2164
nodeLinker: node-modules

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@3":
    peerDependencies:
      typescript: "*"
  "@putout/compare@8":
    peerDependencies:
      try-catch: "*"
  "@putout/engine-parser@4":
    peerDependencies:
      try-catch: "*"
  "@putout/engine-processor@>=3 <5":
    peerDependencies:
      "@babel/preset-env": "*"
  "@putout/operator-add-args@2":
    peerDependencies:
      try-catch: "*"
  "@putout/operator-declare@3":
    peerDependencies:
      try-catch: "*"
  "@putout/traverse@4":
    peerDependencies:
      try-catch: "*"
  "@shopify/eslint-plugin@41":
    peerDependencies:
      "@babel/core": "*"
      graphql: "*"
      prettier: "*"
      typescript: "*"
  eslint-config-hardcore@24:
    peerDependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
      graphql: "*"
  eslint-plugin-graphql@4:
    peerDependencies:
      typescript: "*"
  graphql-config@3:
    peerDependencies:
      typescript: "*"
  putout@24:
    peerDependencies:
      "@babel/preset-env": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
