yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependencies:
      typescript: "*"
  "@shopify/eslint-plugin@*":
    peerDependencies:
      graphql: "*"
      prettier: "*"
      typescript: "*"
  eslint-config-hardcore@*:
    peerDependencies:
      graphql: "*"
  eslint-plugin-graphql@*:
    peerDependencies:
      typescript: "*"
  graphql-config@*:
    peerDependencies:
      typescript: "*"
